name: xmonad-dad
ghc-options: -Wall -O2 -fspecialise-aggressively

dependencies:
  - base

library:
  dependencies:
    - xmonad
  main: Lib.hs
  source-dirs: src

executables:
  xmonad-dad:
    dependencies:
      - containers
      - X11
      - xmonad
      - xmonad-contrib
      - xmonad-dad
    main: Main.hs
    source-dirs: exec
